### PR TITLE
Fixes

### PR DESCRIPTION
**Pull request by ziggi**
- Fixed code indentation (I don't understand why you have so big troubles with this)
- Real fix for WOW_GetTickCountDiff (You can check tests here: Southclaw/ScavengeSurvive#294
- Replace format(..., "%s", ...) by more faster WOW_strcpy

### CODE REVIEW

**Comment by WoutProvost** [comment]
- Indentation: the .inc file (which is the include file) has the exact same contents as the .pwn file (which is the source file). The reason the indentation is of, is because I just copy the contents from the source file into the include file, whenever I'm done editing. I figured no one would ever have to look in the include file, so I didn't bother about the indentation. The reason there are 2 files, is because one day i plan to convert this include to a plugin. But unfortunately I don't know C++ yet and have no knowledge of writing plugins.
- I didn't know the code was wrong. I got the solution from the link posted on this wiki page [GetTickCount](https://wiki.sa-mp.com/wiki/GetTickCount), which you have edited I see. Thanks for pointing that out and editing the wiki.
- I always wondered if that could be done in a more efficient way. Never actually asked on the forums though. Thanks for fixing those lines.

Changes will be added to the source and include files (No need to merge, since I'll have to edit the source file anyway.)
Credits will be given.

**Comment by WoutProvost** [comment]
Why wouldn't I just use [strcat](https://wiki.sa-mp.com/wiki/Strcat) instead of the function you created?
I don't understand why you need to do **result[0] = 0;**

**Comment by ziggi** [comment]
Because strcat concatenate two strings.

**Comment by WoutProvost** [comment]
Ah yes, of course. That line sets the null terminator at the first position so strcat puts the source string at the first position instead of where it could have been if the destination string was not empty.

**Comment by WoutProvost** [comment]
Fixes added in [this](https://github.com/WoutProvost/FCNPC-Boss/commit/8f9ed84393dc9ff511d548848054411f8337f19b) commit.

**Pull request closed without merging**
